import * as Console from "effect/Console";
import * as Effect from "effect/Effect";
import { FileSystem } from "effect/FileSystem";
import * as Option from "effect/Option";
import { Path } from "effect/Path";
import { Argument, Command, Flag } from "effect/unstable/cli";
import { MotionCliError } from "../MotionCliError.js";

const studioArgs = {
	file: Argument.optional(
		Argument.string("file").pipe(
			Argument.withDescription(
				"Studio entrypoint (default ./studio.ts) — a module default-exporting studioConfig({ scenes, layers })",
			),
		),
	),
	port: Flag.optional(Flag.integer("port")),
	host: Flag.optional(Flag.string("host")),
};

/** Shipped studio app source (dist/commands/studio.js → ../../studio-app). */
const studioAppSource = (path: Path) =>
	path.join(
		path.dirname(new URL(import.meta.url).pathname),
		"..",
		"..",
		"studio-app",
	);

/** Built CLI modules the app imports at runtime (dist/commands → dist). */
const distSource = (path: Path) =>
	path.join(path.dirname(new URL(import.meta.url).pathname), "..");

// The studio app is copied INTO the project (.motion/studio) so its bare
// imports (react, @effect-motion/react, the entrypoint's own imports)
// resolve against the project's node_modules — the same graph render uses.
// The StudioConfig contract module (and its error dependency) are copied
// from the CLI's own build so the app and the CLI share ONE brand and one
// entry-normalization implementation. The generated entry.ts STATICALLY
// imports the user's entrypoint through /@fs, which places the entire
// scene graph inside Vite's module graph — ordinary HMR then covers scene
// edits, additions, and removals with no bespoke watchers.
const prepareStudioDir = (projectRoot: string, entryAbs: string) =>
	Effect.gen(function* () {
		const fs = yield* FileSystem;
		const path = yield* Path;
		const source = studioAppSource(path);
		const dist = distSource(path);
		const studioDir = path.join(projectRoot, ".motion", "studio");
		yield* fs.makeDirectory(studioDir, { recursive: true });
		for (const entry of yield* fs.readDirectory(source)) {
			// the in-repo StudioConfig.ts is a typecheck stub re-exporting the
			// CLI source; the built dist module replaces it below (a copied
			// stub would shadow the .js in vite's resolution)
			if (entry === "StudioConfig.ts") {
				continue;
			}
			yield* fs.copyFile(path.join(source, entry), path.join(studioDir, entry));
		}
		for (const module of ["StudioConfig.js", "MotionCliError.js"]) {
			yield* fs.copyFile(path.join(dist, module), path.join(studioDir, module));
		}
		yield* fs.writeFileString(
			path.join(studioDir, "entry.ts"),
			[
				"// generated by `motion studio` — do not edit",
				`import config from "/@fs${entryAbs}";`,
				`export const studioPath = ${JSON.stringify(entryAbs)};`,
				"export default config;",
				"",
			].join("\n"),
		);
		return studioDir;
	}).pipe(
		Effect.mapError((cause) =>
			cause instanceof MotionCliError
				? cause
				: new MotionCliError({
						reason: "StudioFailed",
						message: `could not prepare the studio app in ${projectRoot}/.motion/studio`,
						cause,
					}),
		),
	);

type StudioInput = {
	readonly file: Option.Option<string>;
	readonly port: Option.Option<number>;
	readonly host: Option.Option<string>;
};

const handler = (input: StudioInput) =>
	Effect.gen(function* () {
		const path = yield* Path;
		const fs = yield* FileSystem;
		const cwd = process.cwd();

		// no discovery walk: the entrypoint is an explicit (or default) path
		const requested = Option.getOrElse(input.file, () => "./studio.ts");
		const entryAbs = path.isAbsolute(requested)
			? requested
			: path.resolve(cwd, requested);
		if (!(yield* Effect.orDie(fs.exists(entryAbs)))) {
			return yield* new MotionCliError({
				reason: "ConfigNotFound",
				message:
					`no studio entrypoint at ${requested} — create a studio.ts that ` +
					"default-exports `studioConfig({ scenes: { ... } })`, or pass a path: " +
					"`motion studio ./my.studio.ts`",
			});
		}
		const projectRoot = path.dirname(entryAbs);

		const studioDir = yield* prepareStudioDir(projectRoot, entryAbs);

		const server = yield* Effect.acquireRelease(
			Effect.tryPromise({
				try: async () => {
					const { createServer } = await import("vite");
					const server = await createServer({
						root: studioDir,
						configFile: false,
						server: {
							...(Option.isSome(input.port) ? { port: input.port.value } : {}),
							...(Option.isSome(input.host) ? { host: input.host.value } : {}),
							fs: { allow: [projectRoot] },
						},
						// one React/effect instance no matter where modules live
						resolve: {
							dedupe: ["react", "react-dom", "effect", "effect-motion"],
						},
						// the studio app's JSX must not depend on the project's
						// tsconfig — scaffolded projects set no `jsx`, and esbuild's
						// fallback is the classic transform, which crashes with
						// "React is not defined" before anything mounts
						esbuild: { jsx: "automatic" },
					});
					await server.listen();
					// the project lives OUTSIDE the vite root (.motion/studio);
					// watch it so edits to graph modules out of root hot-reload
					// (vite's default ignores cover node_modules/.git)
					server.watcher.add(projectRoot);
					return server;
				},
				catch: (cause) =>
					new MotionCliError({
						reason: "StudioFailed",
						message: `could not start the studio dev server for ${projectRoot}`,
						cause,
					}),
			}),
			(server) => Effect.promise(() => server.close()),
		);

		yield* Console.log("motion studio running:");
		server.printUrls();

		// serve until interrupted (Ctrl-C) — teardown runs via the scope
		yield* Effect.never;
	}).pipe(Effect.scoped);

export const studioCommand = Command.make("studio", studioArgs, handler).pipe(
	Command.withDescription(
		"Preview the scenes registered in a studio.ts entrypoint (Player + picker)",
	),
);
