import * as Console from "effect/Console";
import * as Effect from "effect/Effect";
import { FileSystem } from "effect/FileSystem";
import * as Option from "effect/Option";
import { Path } from "effect/Path";
import * as Result from "effect/Result";
import { Command, Flag } from "effect/unstable/cli";
import { findConfig } from "../ConfigLoader.js";
import { MotionCliError } from "../MotionCliError.js";

const studioFlags = {
	config: Flag.optional(Flag.string("config")),
	port: Flag.optional(Flag.integer("port")),
	host: Flag.optional(Flag.string("host")),
};

/** Shipped studio app source (dist/commands/studio.js → ../../studio-app). */
const studioAppSource = (path: Path) =>
	path.join(
		path.dirname(new URL(import.meta.url).pathname),
		"..",
		"..",
		"studio-app",
	);

// The studio app is copied INTO the project (.motion/studio) so its bare
// imports (react, @effect-motion/react, the config's own imports) resolve
// against the project's node_modules — the same graph render uses. The
// generated project.ts pins the project root for /@fs imports.
const prepareStudioDir = (projectRoot: string) =>
	Effect.gen(function* () {
		const fs = yield* FileSystem;
		const path = yield* Path;
		const source = studioAppSource(path);
		const studioDir = path.join(projectRoot, ".motion", "studio");
		yield* fs.makeDirectory(studioDir, { recursive: true });
		for (const entry of yield* fs.readDirectory(source)) {
			yield* fs.copyFile(path.join(source, entry), path.join(studioDir, entry));
		}
		yield* fs.writeFileString(
			path.join(studioDir, "project.ts"),
			`// generated by \`motion studio\` — do not edit\nexport const projectRoot = ${JSON.stringify(projectRoot)};\n`,
		);
		return studioDir;
	}).pipe(
		Effect.mapError((cause) =>
			cause instanceof MotionCliError
				? cause
				: new MotionCliError({
						reason: "StudioFailed",
						message: `could not prepare the studio app in ${projectRoot}/.motion/studio`,
						cause,
					}),
		),
	);

type StudioInput = {
	readonly config: Option.Option<string>;
	readonly port: Option.Option<number>;
	readonly host: Option.Option<string>;
};

const handler = (input: StudioInput) =>
	Effect.gen(function* () {
		const path = yield* Path;
		const cwd = process.cwd();

		// a config is optional for studio: unregistered scenes are previewable,
		// so "no config" just means "project root = cwd"
		const found = yield* Effect.result(
			findConfig(cwd, Option.getOrUndefined(input.config)),
		);
		const projectRoot = Result.isSuccess(found)
			? path.dirname(found.success)
			: cwd;

		const studioDir = yield* prepareStudioDir(projectRoot);

		const server = yield* Effect.acquireRelease(
			Effect.tryPromise({
				try: async () => {
					const { createServer } = await import("vite");
					const server = await createServer({
						root: studioDir,
						configFile: false,
						server: {
							...(Option.isSome(input.port) ? { port: input.port.value } : {}),
							...(Option.isSome(input.host) ? { host: input.host.value } : {}),
							fs: { allow: [projectRoot] },
						},
						// one React/effect instance no matter where modules live
						resolve: {
							dedupe: ["react", "react-dom", "effect", "effect-motion"],
						},
						plugins: [
							{
								name: "motion:project-watch",
								configureServer(server) {
									// the project lives OUTSIDE the vite root
									// (.motion/studio); vite's own add/unlink → glob
									// invalidation doesn't reach out-of-root dirs, so
									// scene add/remove refreshes the picker here
									// (ponytail: invalidateAll + full reload — coarse,
									// but studio-sized; narrow it if it ever matters)
									const onAddUnlink = (file: string) => {
										if (!file.startsWith(projectRoot)) return;
										server.moduleGraph.invalidateAll();
										server.ws.send({ type: "full-reload" });
									};
									server.watcher.on("add", onAddUnlink);
									server.watcher.on("unlink", onAddUnlink);
								},
							},
						],
					});
					await server.listen();
					// out-of-root project files aren't watched by default — without
					// this, editing a scene or the config would not hot reload
					server.watcher.add([
						`${projectRoot}/src`,
						`${projectRoot}/motion.config.ts`,
					]);
					return server;
				},
				catch: (cause) =>
					new MotionCliError({
						reason: "StudioFailed",
						message: `could not start the studio dev server for ${projectRoot}`,
						cause,
					}),
			}),
			(server) => Effect.promise(() => server.close()),
		);

		yield* Console.log("motion studio running:");
		server.printUrls();

		// serve until interrupted (Ctrl-C) — teardown runs via the scope
		yield* Effect.never;
	}).pipe(Effect.scoped);

export const studioCommand = Command.make("studio", studioFlags, handler).pipe(
	Command.withDescription(
		"Preview scenes in the browser with hot reload (Player + scene picker)",
	),
);
