import { Player, type PlayerProps } from "@effect-motion/react";
import { useMemo, useState } from "react";
// generated by `motion studio`: statically re-exports the user's studio.ts,
// which places the entire scene graph in Vite's module graph (ordinary HMR
// covers scene edits/additions/removals — no bespoke watchers)
import studioModule, { studioPath } from "./entry";
// the CLI's own contract module, copied beside the app at prepare time —
// one brand, one entry-normalization implementation, shared with `motion`
import {
	type ResolvedEntry,
	resolveEntries,
	type StudioConfig,
	StudioConfigTypeId,
} from "./StudioConfig";

// selection survives the full-page reloads that scene edits trigger
const selectionFromHash = () =>
	decodeURIComponent(window.location.hash.slice(1)) || null;

type Resolved =
	| { readonly _tag: "ready"; readonly entries: ReadonlyArray<ResolvedEntry> }
	| { readonly _tag: "error"; readonly message: string };

const resolve = (): Resolved => {
	try {
		return {
			_tag: "ready",
			entries: resolveEntries(studioModule, studioPath),
		};
	} catch (error) {
		return {
			_tag: "error",
			message: error instanceof Error ? error.message : String(error),
		};
	}
};

// the config's layers cover the union of every registered scene's
// resources (typed in the user's studio.ts); the dynamic boundary here is
// backed by that authoring-time check
const configLayers =
	typeof studioModule === "object" &&
	studioModule !== null &&
	StudioConfigTypeId in studioModule
		? (studioModule as StudioConfig).layers
		: undefined;

export const App = () => {
	const [selected, setSelected] = useState<string | null>(selectionFromHash);
	const resolved = useMemo(resolve, []);

	if (resolved._tag === "error") {
		return (
			<main className="studio-main">
				<div className="studio-error">
					<h2>Studio entrypoint failed to load</h2>
					<pre>{resolved.message}</pre>
				</div>
			</main>
		);
	}

	const entries = resolved.entries;
	const entry = entries.find((e) => e.key === selected) ?? entries[0];

	return (
		<>
			<nav className="studio-sidebar">
				<h1>Scenes</h1>
				{entries.map((e) => (
					<button
						key={e.key}
						type="button"
						className="studio-scene-button"
						data-active={e.key === entry?.key}
						onClick={() => {
							window.location.hash = encodeURIComponent(e.key);
							setSelected(e.key);
						}}
					>
						{e.label}
						{e.label !== e.key && <small>{e.key}</small>}
					</button>
				))}
			</nav>
			<main className="studio-main">
				{entry !== undefined &&
					(() => {
						// options.fps is a preview override of the scene's own rate,
						// so it lands in settings.frameRate (the Player's one clock,
						// which wins over its fps prop); everything else is a plain
						// Player prop and wins over the studio defaults
						const {
							fps,
							settings: entrySettings,
							...playerProps
						} = entry.options;
						const settings =
							fps !== undefined
								? { ...entrySettings, frameRate: fps }
								: entrySettings;
						return (
							<Player
								key={entry.key}
								scene={entry.scene as PlayerProps["scene"] as never}
								autoPlay
								defaultRepeatMode
								{...(settings !== undefined ? { settings } : {})}
								{...(configLayers !== undefined
									? { renderLayers: configLayers as never }
									: {})}
								{...playerProps}
							/>
						);
					})()}
			</main>
		</>
	);
};
